### ISSUE TITLE
Why not to build win32?

### ISSUE THREAD

**Issue by TheDrive2** [tothphu/heimdall_build#1]
1. Thank you for your support.
2. Why not to build Heimdall 1.4.2 for Win32 too???
3. Why not to build the whole bundles with req'd libs?
4. Why not to build Linux/MacOS binaries (expect it would be not so easy to test them so its optional)
5. Why not to pull the whole project to make one more place to get the whole project (incl bins)?

There is a problem for ppl to establish the whole compilation environment, look and configure all the dependencies, etc. If one made it done why not to compile for all...
Programmers are often stay in their own matrix being sure everyone has multiGB compilation environment on their PC... Most user just want to get one-click solution for their problems. Geeks want to get the useful tool they could execute in the different manners, but they also want to get it complete. They often DL sources to for archival purposes. Once some solution can be done via source edition there will be reasonable to establish environment.

**Comment by tothphu** [comment]
Simple: I needed to do it because I wanted to run it. Spent loads of time doing it. I've shared what I've achieved.

I'm not the maintainer of heimdall just +1 user.
